import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import HeaderTop from "./components/HeaderTop/HeaderTop";
import HeaderBottom from "./components/HeaderBottom/HeaderBottom";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Basel Almomani Merwas Task ",
  description: "Generated by Basel Almoamni & NextJs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <HeaderBottom />
        {children}
        <Footer />
      </body>
    </html>
  );
}


